### ISSUE TITLE
Linker errors with vcpkg package and systems other than Windows

### ISSUE THREAD

**Issue by t1meshift** [brainboxdotcc/DPP#706]
**Git commit reference**
DPP v10.0.24 from vcpkg baseline `2f56fdad4bcf43c21ec6f952cf7b91c8c43c5c0d`

**Describe the bug**

I wrote a simple bot using DPP and vcpkg, compiled it on a Windows machine with MSVC 2022, and it works like a charm.

Unfortunately, I can't say the same about the build process using WSL2 (Ubuntu 22.04). So, vcpkg integration does work (all dependencies have been downloaded and configured), object files are generated, but a build fails with a bunch of linker errors: 

<details><summary>Something about `ld` unable to find dependant libraries</summary>
<p>

```
FAILED: discord_target_replier
: && /usr/bin/c++ -O3 -DNDEBUG  CMakeFiles/discord_target_replier.dir/main.cpp.o CMakeFiles/discord_target_replier.dir/Config.cpp.o -o discord_target_replier  vcpkg_installed/x64-linux/lib/libdpp.a && cd /mnt/c/dev/discord_target_replier/cmake-build-linux-release && /usr/bin/cmake -E copy_if_different /mnt/c/dev/discord_target_replier/config.example.json /mnt/c/dev/discord_target_replier/cmake-build-linux-release
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(discordclient.cpp.o): in function `dpp::discord_client::setup_zlib()':
discordclient.cpp:(.text+0xc42): undefined reference to `inflateInit_'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(discordclient.cpp.o): in function `dpp::discord_client::end_zlib()':
discordclient.cpp:(.text+0xc8c): undefined reference to `inflateEnd'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(discordclient.cpp.o): in function `dpp::discord_client::handle_frame(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
discordclient.cpp:(.text+0x7659): undefined reference to `inflate'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(discordvoiceclient.cpp.o): in function `dpp::discord_voice_client::cleanup()':
discordvoiceclient.cpp:(.text+0x109d): undefined reference to `opus_encoder_destroy'
/usr/bin/ld: discordvoiceclient.cpp:(.text+0x10b9): undefined reference to `opus_repacketizer_destroy'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(discordvoiceclient.cpp.o): in function `dpp::discord_voice_client::encode(unsigned char*, unsigned long, unsigned char*, unsigned long&)':
discordvoiceclient.cpp:(.text+0x36dd): undefined reference to `opus_repacketizer_init'
/usr/bin/ld: discordvoiceclient.cpp:(.text+0x3717): undefined reference to `opus_repacketizer_cat'
/usr/bin/ld: discordvoiceclient.cpp:(.text+0x3754): undefined reference to `opus_encode'
/usr/bin/ld: discordvoiceclient.cpp:(.text+0x377c): undefined reference to `opus_strerror'
/usr/bin/ld: discordvoiceclient.cpp:(.text+0x38c6): undefined reference to `opus_repacketizer_out'
/usr/bin/ld: discordvoiceclient.cpp:(.text+0x391d): undefined reference to `opus_strerror'
/usr/bin/ld: discordvoiceclient.cpp:(.text+0x3c0d): undefined reference to `opus_strerror'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(discordvoiceclient.cpp.o): in function `dpp::discord_voice_client::discord_voice_client(dpp::cluster*, dpp::snowflake, dpp::snowflake, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
discordvoiceclient.cpp:(.text+0x4325): undefined reference to `sodium_init'
/usr/bin/ld: discordvoiceclient.cpp:(.text+0x4353): undefined reference to `opus_encoder_create'
/usr/bin/ld: discordvoiceclient.cpp:(.text+0x436b): undefined reference to `opus_repacketizer_create'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(discordvoiceclient.cpp.o): in function `dpp::discord_voice_client::voice_courier_loop(dpp::discord_voice_client&, dpp::discord_voice_client::courier_shared_state_t&)':
discordvoiceclient.cpp:(.text+0x53c9): undefined reference to `opus_decode'
/usr/bin/ld: discordvoiceclient.cpp:(.text+0x542e): undefined reference to `opus_decode'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(discordvoiceclient.cpp.o): in function `dpp::discord_voice_client::read_ready()':
discordvoiceclient.cpp:(.text+0x7d3c): undefined reference to `crypto_secretbox_open_easy'
/usr/bin/ld: discordvoiceclient.cpp:(.text+0x81a9): undefined reference to `opus_decoder_create'
/usr/bin/ld: discordvoiceclient.cpp:(.text+0x81ed): undefined reference to `opus_decoder_destroy'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(discordvoiceclient.cpp.o): in function `dpp::discord_voice_client::send_audio_opus(unsigned char*, unsigned long, unsigned long)':
discordvoiceclient.cpp:(.text+0x931e): undefined reference to `crypto_secretbox_easy'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(discordvoiceclient.cpp.o): in function `dpp::discord_voice_client::send_audio_opus(unsigned char*, unsigned long)':
discordvoiceclient.cpp:(.text+0x94ee): undefined reference to `opus_packet_get_nb_samples'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(discordvoiceclient.cpp.o): in function `std::_Function_handler<void (OpusDecoder&), dpp::discord_voice_client::set_user_gain(dpp::snowflake, float)::{lambda(OpusDecoder&)#1}>::_M_invoke(std::_Any_data const&, OpusDecoder&)':
discordvoiceclient.cpp:(.text+0x26): undefined reference to `opus_decoder_ctl'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(discordvoiceclient.cpp.o): in function `dpp::discord_voice_client::read_ready() [clone .cold]':
discordvoiceclient.cpp:(.text.unlikely+0x1288): undefined reference to `opus_decoder_destroy'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(etf.cpp.o): in function `dpp::etf_parser::decode_compressed[abi:cxx11]()':
etf.cpp:(.text+0x2bec): undefined reference to `uncompress'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(sslclient.cpp.o): in function `dpp::ssl_client::write(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
sslclient.cpp:(.text+0x8b): undefined reference to `SSL_write'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(sslclient.cpp.o): in function `dpp::ssl_client::connect()':
sslclient.cpp:(.text+0x372): undefined reference to `SSL_new'
/usr/bin/ld: sslclient.cpp:(.text+0x391): undefined reference to `SSL_set_fd'
/usr/bin/ld: sslclient.cpp:(.text+0x3ab): undefined reference to `SSL_ctrl'
/usr/bin/ld: sslclient.cpp:(.text+0x3f9): undefined reference to `SSL_connect'
/usr/bin/ld: sslclient.cpp:(.text+0x40e): undefined reference to `SSL_get_current_cipher'
/usr/bin/ld: sslclient.cpp:(.text+0x416): undefined reference to `SSL_CIPHER_get_name'
/usr/bin/ld: sslclient.cpp:(.text+0x461): undefined reference to `TLS_client_method'
/usr/bin/ld: sslclient.cpp:(.text+0x469): undefined reference to `SSL_CTX_new'
/usr/bin/ld: sslclient.cpp:(.text+0x48a): undefined reference to `SSL_CTX_ctrl'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(sslclient.cpp.o): in function `dpp::ssl_client::read_loop()':
sslclient.cpp:(.text+0x9e8): undefined reference to `SSL_read'
/usr/bin/ld: sslclient.cpp:(.text+0x9fa): undefined reference to `SSL_get_error'
/usr/bin/ld: sslclient.cpp:(.text+0xa29): undefined reference to `SSL_pending'
/usr/bin/ld: sslclient.cpp:(.text+0xa4d): undefined reference to `SSL_shutdown'
/usr/bin/ld: sslclient.cpp:(.text+0xab8): undefined reference to `SSL_write'
/usr/bin/ld: sslclient.cpp:(.text+0xaca): undefined reference to `SSL_get_error'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(sslclient.cpp.o): in function `dpp::ssl_client::close() [clone .localalias]':
sslclient.cpp:(.text+0x107d): undefined reference to `SSL_free'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(sslclient.cpp.o): in function `dpp::ssl_client::cleanup()':
sslclient.cpp:(.text+0x13bd): undefined reference to `SSL_free'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libdpp.a(sslclient.cpp.o): in function `dpp::ssl_client::ssl_client(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool)':
sslclient.cpp:(.text+0x19f4): undefined reference to `SSL_free'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

</p>
</details> 

**To Reproduce**
1. Install vcpkg
2. Clone https://github.com/t1meshift/discord-target-replier/
3. Build it:
    - `cd discord_target_replier/`
    - `cmake -S . -B build -GNinja -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake`
    - `cmake --build build`
4. Observe ld errors :(

**Expected behavior**
Successful executable build

**System Details:**
 - OS: WSL2 with Ubuntu 22.04
 - CMake 3.22+
 - GCC 11.2.0/Clang 14.0
 - vcpkg baseline `2f56fdad4bcf43c21ec6f952cf7b91c8c43c5c0d`

**Additional context**
I know that Microsoft products work as expected only on Windows, but I just don't want to build DPP from source and manage dependencies manually, and CLion has vcpkg support.

**Comment by braindigitalis** [comment]
why not just use the prebuilt dpp for debian, which works fine in 22.04 wsl?

**Comment by braindigitalis** [comment]
please show link errors.
im guessing though that your use of nlohmann json on line 19 is the issue, as dpp already publically uses nlohmann.

**Comment by braindigitalis** [comment]
closing due to lack of feedback, we can't identify issue without errors

**Comment by braindigitalis** [comment]
Just found your errors buried in a collapsed section?
However looks to be user error in that you arent specifying the correct build flags. No -std=c++17, etc. Also possibly building a 32 bit build? Not sure from what i see,
`/usr/bin/c++ -O3 -DNDEBUG  CMakeFiles/discord_target_replier.dir/main.cpp.o CMakeFiles/discord_target_replier.dir/Config.cpp.o -o discord_target_replier  vcpkg_installed/x64-linux/lib/libdpp.a `
Please try following the guide on dpp.dev.
