### ISSUE TITLE
Modals are broken on latest dev

### ISSUE THREAD

**Issue by Mishura4** [brainboxdotcc/DPP#946]
Reported by @Neko-Life on Discord, modal APIs are broken, giving this
```json
{"message": "Invalid Form Body", "code": 50035, "errors": {"data": {"custom_id": {"_errors": [{"code": "BASE_TYPE_REQUIRED", "message": "This field is required"}]}, "title": {"_errors": 
[{"code": "BASE_TYPE_REQUIRED", "message": "This field is required"}]}, "components": {"_errors": [{"code": "BASE_TYPE_BAD_LENGTH", "message": "Must be between 1 and 5 in length."}]}}}}
```

This would likely be a problem with a modal's `fill_from_json_impl` method.

Culprit commit seems to be https://github.com/brainboxdotcc/DPP/commit/d2322315aa661c175bbbed152d0ccac8f29e33b3

Additionally trying to build a modal's json gives a compilation error:
```
<redacted>/Musicat/src/musicat/cmds/search.cpp: In function ‘dpp::interaction_modal_response musicat::command::search::modal_enqueue_searched_track_top()’:
<redacted>/Musicat/src/musicat/cmds/search.cpp:53:24: error: request for member ‘to_json’ is ambiguous
   53 |     std::cerr << modal.to_json(true).dump(2) << '\n';
      |                        ^~~~~~~
```
The fix for this one would be to import one of the bases's methods with `using`.

I probably won't have time to fix this until Monday, though someone else can look at it if they want to.

**Comment by Jaskowicz1** [comment]
There is now a hot fix to correct this issue. We're looking at further improvements to the fix, however, this issue is now resolved.
